#!/bin/bash
#
# rma		Start up the Hostmonitor rma daemon
#
# chkconfig: 2345 55 25
# description: RMA is small application that accepts requests from HostMonitor, \
#	performs test (or action) and provides information about test result back to HostMonitor.
#
# processname: rma
# config: /usr/local/etc/rma.ini
# pidfile: /var/run/rma.pid

### BEGIN INIT INFO
# Provides: rma
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Host Monitor RMA
# Description:       Host Monitor RMA
#		     
### END INIT INFO

# source function library
. /etc/rc.d/init.d/functions


RETVAL=0
prog="rma"
lockfile=/var/lock/subsys/$prog
OPTIONS=

# Some functions to make the below more readable
RMA=/usr/local/sbin/rma
PID_FILE=/var/run/rma.pid

runlevel=$(set -- $(runlevel); eval "echo \$$#" )

fips_enabled() {
	if [ -r /proc/sys/crypto/fips_enabled ]; then
		cat /proc/sys/crypto/fips_enabled
	else
		echo 0
	fi
}


start()
{
	[ -x $RMA ] || exit 5
	[ -f /usr/local/etc/rma.ini ] || exit 6
	
	echo -n $"Starting $prog: "
	$RMA $OPTIONS /usr/local/etc/rma.ini &>/dev/null  && success || failure
	RETVAL=$?
	[ $RETVAL -eq 0 ] && touch $lockfile
        [ $RETVAL -eq 0 ] && echo "$(ps ax | grep ${RMA} | grep -v grep | awk '{print $1}')" > $PID_FILE
	echo
	return $RETVAL
}

stop()
{
	echo -n $"Stopping $prog: "
	killproc -p $PID_FILE $RMA
	RETVAL=$?
	[ $RETVAL -eq 0 ] && rm -f $lockfile
	echo
}

reload()
{
	echo -n $"Reloading $prog: "
	killproc -p $PID_FILE $RMA -HUP
	RETVAL=$?
	echo
}

restart() {
	stop
	start
}

force_reload() {
	restart
}

rh_status() {
echo $PID_FILE
	status -p $PID_FILE rma
}

rh_status_q() {
	rh_status >/dev/null 2>&1
}

case "$1" in
	start)
		rh_status_q && exit 0
		start
		;;
	stop)
		if ! rh_status_q; then
			rm -f $lockfile
			exit 0
		fi
		stop
		;;
	restart)
		restart
		;;
	reload)
		rh_status_q || exit 7
		reload
		;;
	destroy)
		destroy
		;;
	status)
		rh_status
		RETVAL=$?
		if [ $RETVAL -eq 3 -a -f $lockfile ] ; then
			RETVAL=2
		fi
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|reload|force-reload|condrestart|try-restart|status}"
		RETVAL=2
esac
exit $RETVAL
